# Generated by Django 6.0.2 on 2026-05-11 04:00

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='Donor who accepted this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='core.donoruser'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Required blood group', max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(blank=True, help_text='City where blood is needed', max_length=100, null=True, validators=[core.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(help_text='Hospital name (at least 3 characters)', max_length=300, validators=[core.validators.validate_hospital]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (-90 to 90)', null=True, validators=[core.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (-180 to 180)', null=True, validators=[core.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number — exactly 10 digits', max_length=10, null=True, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='quantity',
            field=models.IntegerField(default=450, help_text='Amount needed in ml (100 – 1000 ml)', validators=[core.validators.validate_quantity]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for blood requirement (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='User who posted this request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.donoruser'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this request', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', help_text='How urgent is this request?', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Blood type donated', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Actual date and time donation was completed', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(help_text='Donor who made this donation', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.donoruser'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(blank=True, help_text='Hospital or location where donation took place', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(default=450, help_text='Amount donated in ml (100 – 1000 ml)', validators=[core.validators.validate_quantity]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Name of the recipient (letters only, 2–100 chars)', max_length=200, null=True, validators=[core.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Linked blood request (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodrequest'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for donation', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', help_text='Current status of this donation', max_length=20),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age must be between 18 and 65', null=True, validators=[core.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='available_to_donate',
            field=models.BooleanField(default=False, help_text='Is the donor currently available to donate?'),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='ABO blood group', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='city',
            field=models.CharField(blank=True, help_text='City name (letters and spaces only)', max_length=100, null=True, validators=[core.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='email',
            field=models.EmailField(help_text='Valid email address (must be unique)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='last_donation',
            field=models.DateField(blank=True, help_text='Date of last donation (cannot be in the future)', null=True, validators=[core.validators.validate_last_donation]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (-90 to 90)', null=True, validators=[core.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (-180 to 180)', null=True, validators=[core.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='name',
            field=models.CharField(help_text='Full name (letters, spaces, dots, hyphens only — 2 to 100 chars)', max_length=100, validators=[core.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='phone',
            field=models.CharField(blank=True, help_text='Exactly 10 digits, no spaces or symbols', max_length=10, null=True, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='URL or file path to profile picture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('admin', 'Admin')], default='recipient', help_text='User role on the platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='state',
            field=models.CharField(blank=True, help_text='State / Province', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='verified',
            field=models.BooleanField(default=False, help_text='Has this user been verified by admin?'),
        ),
        migrations.AlterField(
            model_name='donoruser',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg (50 – 200 kg)', null=True, validators=[core.validators.validate_weight]),
        ),
        migrations.AlterField(
            model_name='match',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Blood type for this match', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='donor',
            field=models.ForeignKey(help_text='Donor in this match', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_donor', to='core.donoruser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='recipient',
            field=models.ForeignKey(help_text='Recipient in this match', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_recipient', to='core.donoruser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Linked blood request (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodrequest'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', help_text='Current match status', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Has the receiver read this message?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(help_text='Message content (max 2000 characters)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(help_text='User who received this message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.donoruser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, help_text='Chat room identifier', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.donoruser'),
        ),
    ]
