# Generated by Django 6.0.2 on 2026-05-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bloodrequest_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='mongo_id',
            field=models.CharField(blank=True, help_text='MongoDB ObjectId — auto-synced', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='certificate_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', help_text='Admin must approve before donor can download certificate', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='mongo_id',
            field=models.CharField(blank=True, help_text='MongoDB ObjectId — auto-synced', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (shown to donor in real-time)', null=True),
        ),
        migrations.AddField(
            model_name='donoruser',
            name='mongo_id',
            field=models.CharField(blank=True, help_text='MongoDB ObjectId — auto-synced from Node.js backend', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this request', max_length=20),
        ),
    ]
