# Generated by Django 6.0.2 on 2026-05-11 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bloodrequest_mongo_id_donation_certificate_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('donor_email', models.EmailField(blank=True, help_text='Email of the donor', max_length=254, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_name', models.CharField(max_length=300)),
                ('donation_date', models.DateField()),
                ('blood_type', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('quantity', models.IntegerField(default=450)),
                ('file_url', models.CharField(blank=True, help_text='URL to uploaded file', max_length=500, null=True)),
                ('file_type', models.CharField(blank=True, help_text='image or pdf', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_certificates', to='core.donoruser')),
            ],
            options={
                'verbose_name': 'Uploaded Certificate',
                'verbose_name_plural': 'Uploaded Certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
